# permissions for end users to edit logics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logic-editor-role
rules:
- apiGroups:
  - databaselogic.example.com
  resources:
  - logics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databaselogic.example.com
  resources:
  - logics/status
  verbs:
  - get
