# permissions for end users to view logics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logic-viewer-role
rules:
- apiGroups:
  - databaselogic.example.com
  resources:
  - logics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databaselogic.example.com
  resources:
  - logics/status
  verbs:
  - get
