apiVersion: databaselogic.example.com/v1alpha1
kind: Logic
metadata:
  name: logic-sample
  labels:
    app: printData
spec:
  size: 1
  appname: epf-data
  appimage: 2016csc044/epfdetails:v1.0.8 # 7, 8 
  sideCarName: reconsile-app
  sideCarImage: 2016csc044/reconsile:v1.0.3 #store request
  schemaChangeApplyName: schema-change-apply-request
  schemaChangeApplyImage: 2016csc044/schema_changes_apply_for_request:v1.0.1 #when update start its runnig
  defaultSchemaImage: 2016csc044/defaultschema:v1.0.1 #default current version schema
  appVersion: v1_0_2
  databaseVersion: v1_0_2
