apiVersion: databaselogic.example.com/v1alpha1
kind: Logic
metadata:
  name: logic-sample
  labels:
    app: printData
spec:
  size: 1
  appname: app
  appimage: 2016csc044/app:v1
  sideCarName: proxy
  sideCarImage: 2016csc044/proxy:v1 #store request
  schemaChangeApplyName: schema-converter
  schemaChangeApplyImage: 2016csc044/schemaconverter:v1 #when update start its runnig
  defaultSchemaImage: 2016csc044/defaultschema:v1 #default current version schema
  appVersion: v1_0_1
  databaseVersion: v1_0_1
